/**
 * Dashboard module — Equipment health monitoring,
 * stats cards, and real-time sensor data visualization.
 */

let dashboardData = {
    stats: null,
    equipment: [],
};

/**
 * Initialize the dashboard.
 */
async function initDashboard() {
    await Promise.all([
        loadDashboardStats(),
        loadEquipment(),
        loadScenarios(),
    ]);

    // Register for real-time sensor updates
    onWsMessage('sensor_update', handleSensorUpdate);

    // Register for action log updates
    onWsMessage('action_log', () => {
        showToast('New ERP/SCADA action generated by AI Agent', 'info');
        loadDashboardStats();
        loadEquipment();
    });
    
    onWsMessage('action_log_update', () => {
        loadDashboardStats();
        loadEquipment();
    });
}

/**
 * Load dashboard statistics.
 */
async function loadDashboardStats() {
    try {
        const role = window.currentUserRole || 'engineer';
        if (role === 'manager') {
            const [statsRes, costRes, actionsRes] = await Promise.all([
                apiRequest('/api/dashboard/stats'),
                apiRequest('/api/analytics/cost-summary'),
                apiRequest('/api/dashboard/actions?limit=10')
            ]);
            dashboardData.stats = statsRes.data;
            const pendingActionsCount = (actionsRes.data || []).filter(a => a.status === 'pending').length;
            renderManagerStatsCards(statsRes.data, costRes.data, pendingActionsCount);
        } else {
            const result = await apiRequest('/api/dashboard/stats');
            dashboardData.stats = result.data;
            renderStatsCards(result.data);
        }
    } catch (error) {
        console.error('Failed to load stats:', error);
    }
}

/**
 * Load equipment list.
 */
async function loadEquipment() {
    try {
        const result = await apiRequest('/api/dashboard/equipment');
        dashboardData.equipment = result.data;
        renderEquipmentGrid(result.data);
        renderDigitalTwin(result.data);
        renderRoleSpecificSection();
    } catch (error) {
        console.error('Failed to load equipment:', error);
    }
}

/**
 * Render stats cards.
 */
function renderStatsCards(stats) {
    const grid = document.getElementById('stats-grid');
    grid.innerHTML = `
        <div class="stat-card">
            <div class="stat-card-label">Total Equipment</div>
            <div class="stat-card-value">${stats.total_equipment}</div>
            <div class="stat-card-footer">Across all zones</div>
        </div>
        <div class="stat-card">
            <div class="stat-card-label">Operational</div>
            <div class="stat-card-value operational">${stats.operational}</div>
            <div class="stat-card-footer">${stats.uptime_percentage}% uptime</div>
        </div>
        <div class="stat-card">
            <div class="stat-card-label">Warning</div>
            <div class="stat-card-value warning">${stats.warning}</div>
            <div class="stat-card-footer">Need attention</div>
        </div>
        <div class="stat-card">
            <div class="stat-card-label">Critical</div>
            <div class="stat-card-value critical">${stats.critical}</div>
            <div class="stat-card-footer">Immediate action required</div>
        </div>
        <div class="stat-card">
            <div class="stat-card-label">Active Alerts</div>
            <div class="stat-card-value" style="color: ${stats.critical_alerts > 0 ? 'var(--status-critical)' : 'var(--text-primary)'}">${stats.active_alerts}</div>
            <div class="stat-card-footer">${stats.critical_alerts} critical</div>
        </div>
        <div class="stat-card">
            <div class="stat-card-label">Recent Maintenance</div>
            <div class="stat-card-value">${stats.recent_maintenance}</div>
            <div class="stat-card-footer">Last 7 days</div>
        </div>
    `;
}

/**
 * Render an animated circular health-score ring for an equipment card.
 * Expects the `health` object returned by the dashboard API
 * ({ score, grade, label, factors }).
 */
function renderHealthRing(health) {
    if (!health || typeof health.score !== 'number') return '';

    const score = Math.max(0, Math.min(100, health.score));
    const grade = (health.grade || 'C').toLowerCase();
    const label = health.label || 'Fair';

    // Geometry: 44x44 viewport, centre 22,22, radius 18 (stroke-width 4).
    const radius = 18;
    const circumference = 2 * Math.PI * radius;
    const offset = circumference * (1 - score / 100);

    const colorMap = {
        a: '#10b981',
        b: '#3b82f6',
        c: '#f59e0b',
        d: '#ef4444',
        f: '#ef4444',
    };
    const stroke = colorMap[grade] || '#f59e0b';

    return `
        <div class="health-ring-container">
            <div class="health-ring">
                <svg viewBox="0 0 44 44">
                    <circle class="health-ring-bg" cx="22" cy="22" r="${radius}"></circle>
                    <circle class="health-ring-fill" cx="22" cy="22" r="${radius}"
                        stroke="${stroke}"
                        stroke-dasharray="${circumference.toFixed(2)}"
                        stroke-dashoffset="${offset.toFixed(2)}"></circle>
                </svg>
                <span class="health-ring-value" style="color:${stroke}">${score}</span>
            </div>
            <div>
                <span class="health-ring-label">Health: ${label}</span>
                <span class="health-ring-grade grade-${grade}">${(health.grade || 'C')}</span>
            </div>
        </div>
    `;
}

/**
 * Render equipment grid.
 */
function renderEquipmentGrid(equipment) {
    const grid = document.getElementById('equipment-grid');
    grid.innerHTML = equipment.map(eq => `
        <div class="equipment-card" onclick="askAboutEquipment('${eq.id}', '${eq.name}')">
            <div class="equipment-card-header">
                <div>
                    <div class="equipment-card-name">${eq.name}</div>
                    <div class="equipment-card-id">${eq.id}</div>
                </div>
                <span class="status-badge ${eq.status}" id="badge-${eq.id}">
                    <span class="status-dot"></span>
                    <span class="status-text">${eq.status}</span>
                </span>
            </div>
            <div class="equipment-card-details">
                <div class="equipment-detail"><span>Zone:</span> ${eq.zone}</div>
                <div class="equipment-detail"><span>Type:</span> ${eq.type}</div>
                <div class="equipment-detail">
                    <span>Criticality:</span>
                    <span class="criticality-badge ${eq.criticality}">${eq.criticality}</span>
                </div>
                <div class="equipment-detail"><span>Last Maint:</span> ${eq.last_maintenance || 'N/A'}</div>
            </div>
            ${renderHealthRing(eq.health)}
        </div>
    `).join('');
}

/**
 * Render digital twin with SVG flow lines.
 */
function renderDigitalTwin(equipment) {
    const container = document.getElementById('digital-twin-container');
    if (!container) return;

    // Define stage info with layout positioning (x, y)
    // and matching equipment ID
    const nodesDef = [
        // Main Production Line (y = 65)
        { id: 'BF-001', name: 'Blast Furnace #1', icon: '🔥', x: 40, y: 65, next: 'BOF-001' },
        { id: 'BOF-001', name: 'BOF Converter #1', icon: '⚗️', x: 200, y: 65, next: 'LF-001' },
        { id: 'LF-001', name: 'Ladle Furnace #1', icon: '⚡', x: 360, y: 65, next: 'CCM-001' },
        { id: 'CCM-001', name: 'Continuous Caster', icon: '🏭', x: 520, y: 65, next: 'HRM-001' },
        { id: 'HRM-001', name: 'Hot Rolling Mill', icon: '⚙️', x: 680, y: 65, next: 'CRM-001' },
        { id: 'CRM-001', name: 'Cold Rolling Mill', icon: '🗜️', x: 840, y: 65, next: null },

        // Auxiliaries / Utilities (y = 220)
        { id: 'CR-001', name: 'Charging Crane', icon: '🏗️', x: 120, y: 220, target: 'BOF-001' },
        { id: 'HP-001', name: 'Hydraulic Press', icon: '🧲', x: 280, y: 220, target: 'LF-001' },
        { id: 'CT-001', name: 'Cooling Tower #3', icon: '💧', x: 440, y: 220, target: 'CCM-001' },
        { id: 'GR-001', name: 'Gas Recovery', icon: '🌬️', x: 600, y: 220, target: 'HRM-001' }
    ];

    // Build map of equipment status
    const eqStatusMap = {};
    equipment.forEach(eq => {
        eqStatusMap[eq.id] = eq.status;
    });

    // Generate HTML for nodes
    let htmlNodesContent = '';
    nodesDef.forEach(node => {
        const status = eqStatusMap[node.id] || 'operational';
        htmlNodesContent += `
            <div class="dt-node-card status-${status}" style="left: ${node.x}px; top: ${node.y}px;" onclick="askAboutEquipment('${node.id}', '${node.name}')">
                <div class="dt-node-card-icon">${node.icon}</div>
                <div class="dt-node-card-name">${node.name}</div>
                <div class="dt-node-card-status ${status}">${status.toUpperCase()}</div>
                <div class="dt-node-readout" id="dt-sensor-${node.id}"></div>
            </div>
        `;
    });

    // Generate SVG path connectors.
    // Each connection draws two stacked paths:
    //   1. the colored status line (subtle, status-coloured dashes)
    //   2. a bright white "pulse" overlay that flows along the path (material flow)
    let svgPathsContent = '';
    nodesDef.forEach(node => {
        const status = eqStatusMap[node.id] || 'operational';
        const flowClass = `flow-${status}`;

        if (node.next) {
            // Find target node coordinates
            const nextNode = nodesDef.find(n => n.id === node.next);
            if (nextNode) {
                // Horizontal path between centers
                const x1 = node.x + 110;
                const y1 = node.y + 37;
                const x2 = nextNode.x;
                const y2 = nextNode.y + 37;
                const d = `M ${x1} ${y1} L ${x2} ${y2}`;
                svgPathsContent += `<path d="${d}" class="dt-flow-path ${flowClass}" />`;
                svgPathsContent += `<path d="${d}" class="dt-flow-pulse ${flowClass}" />`;
            }
        }

        if (node.target) {
            // Curved path from auxiliary to target
            const targetNode = nodesDef.find(n => n.id === node.target);
            if (targetNode) {
                const x1 = node.x + 55;
                const y1 = node.y;
                const x2 = targetNode.x + 55;
                const y2 = targetNode.y + 75;
                const cpY1 = y1 - 40;
                const cpY2 = y2 + 40;
                const d = `M ${x1} ${y1} C ${x1} ${cpY1}, ${x2} ${cpY2}, ${x2} ${y2}`;
                svgPathsContent += `<path d="${d}" class="dt-flow-path ${flowClass}" />`;
                svgPathsContent += `<path d="${d}" class="dt-flow-pulse ${flowClass}" />`;
            }
        }
    });

    // Inject layout wrapper
    container.innerHTML = `
        <div class="dt-plant-wrapper">
            <!-- HTML Nodes Layer -->
            <div class="dt-html-nodes">
                ${htmlNodesContent}
            </div>
            <!-- SVG Connectors Layer -->
            <svg class="dt-svg-overlay" width="100%" height="100%" viewBox="0 0 1000 350">
                ${svgPathsContent}
            </svg>
        </div>
    `;
}

/**
 * Navigate to chat and ask about a specific equipment.
 */
function askAboutEquipment(id, name) {
    switchView('chat');
    const input = document.getElementById('chat-input');
    input.value = `What is the current status and any issues with ${name} (${id})?`;
    input.focus();
}

/**
 * Handle real-time sensor updates.
 */
function handleSensorUpdate(data) {
    if (!Array.isArray(data)) return;

    // Live-update the Digital Twin node overlays with the latest readings.
    updateTwinSensors(data);

    // Update equipment status if any anomalies
    const hasAnomalies = data.some(r => r.is_anomaly);
    if (hasAnomalies) {
        // Refresh stats periodically (debounced)
        debouncedRefreshStats();
    }
}

/**
 * Update the always-visible live sensor readout below each Digital Twin node.
 * Shows the 2 most important metrics (e.g. temperature + vibration) compactly,
 * positioned below the card so it never overlaps neighbouring boxes.
 */
function updateTwinSensors(readings) {
    const byEquipment = {};
    readings.forEach(r => {
        if (!byEquipment[r.equipment_id]) byEquipment[r.equipment_id] = [];
        byEquipment[r.equipment_id].push(r);
    });

    const priority = ['temperature', 'vibration', 'pressure', 'flow_rate', 'casting_speed',
                      'oil_temperature', 'hydraulic_pressure', 'load_weight', 'gas_flow',
                      'dust_level', 'water_temp_in', 'motor_current', 'electrode_current'];

    const iconFor = (metric) => (
          metric === 'temperature'       ? '🌡️'
        : metric === 'vibration'         ? '📳'
        : metric === 'fan_vibration'     ? '📳'
        : metric === 'pressure'          ? '🔵'
        : metric === 'flow_rate'         ? '💧'
        : metric === 'casting_speed'     ? '⚡'
        : metric === 'load_weight'       ? '🏋️'
        : metric === 'dust_level'        ? '🌫️'
        : metric === 'oil_temperature'   ? '🛢️'
        : metric === 'hydraulic_pressure'? '🔩'
        : metric === 'gas_flow'          ? '💨'
        : '⚡');

    Object.keys(byEquipment).forEach(eqId => {
        const readout = document.getElementById(`dt-sensor-${eqId}`);
        if (!readout) return;

        const metrics = byEquipment[eqId];

        // Deduplicate by metric (keep latest occurrence first)
        const byMetric = {};
        metrics.forEach(m => { if (!(m.metric in byMetric)) byMetric[m.metric] = m; });

        // Always prefer a TEMPERATURE-type and a VIBRATION-type reading so every
        // card consistently shows "°C  ·  mm/s".
        const tempKeys = ['temperature', 'oil_temperature', 'water_temp_in', 'hoist_motor_temp'];
        const vibKeys  = ['vibration', 'fan_vibration'];

        const pick = (keys) => { for (const k of keys) if (byMetric[k]) return byMetric[k]; return null; };
        const chosen = [];
        const tempM = pick(tempKeys);
        const vibM  = pick(vibKeys);
        if (tempM) chosen.push(tempM);
        if (vibM)  chosen.push(vibM);

        // Fallback: if a card has neither, show its top 2 metrics by priority.
        if (chosen.length < 2) {
            const sorted = Object.values(byMetric).sort((a, b) => {
                const ia = priority.indexOf(a.metric);
                const ib = priority.indexOf(b.metric);
                return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib);
            });
            for (const m of sorted) {
                if (chosen.length >= 2) break;
                if (!chosen.includes(m)) chosen.push(m);
            }
        }

        const cells = chosen.slice(0, 2).map(m => {
            const cls = m.is_anomaly ? 'anomaly' : (m.early_warning ? 'warn' : '');
            return `<span class="dt-ro-cell ${cls}">${iconFor(m.metric)} ${m.value}<small>${m.unit || ''}</small></span>`;
        }).join('');

        if (cells) {
            readout.innerHTML = cells;
            readout.classList.add('has-data');
        }
    });
}

const debouncedRefreshStats = debounce(async () => {
    await Promise.all([
        loadDashboardStats(),
        loadEquipment(),
    ]);
}, 5000);


/**
 * Render manager-specific KPI cards.
 */
function renderManagerStatsCards(stats, cost, pendingCount) {
    const grid = document.getElementById('stats-grid');
    if (!grid) return;
    
    const formatINR = (val) => {
        const lakhs = val / 100000;
        if (lakhs >= 100) {
            return `₹${(lakhs / 100).toFixed(2)} Cr`;
        }
        return `₹${lakhs.toFixed(1)} Lakhs`;
    };

    const annualRisk = cost.annual_downtime_risk.total;
    const netSavings = cost.roi.net_savings;
    const uptime = stats.uptime_percentage;

    grid.innerHTML = `
        <div class="stat-card">
            <div class="stat-card-label">Annual Downtime Risk</div>
            <div class="stat-card-value critical">${formatINR(annualRisk)}</div>
            <div class="stat-card-footer">Estimated exposure</div>
        </div>
        <div class="stat-card">
            <div class="stat-card-label">Net Savings (Preventive)</div>
            <div class="stat-card-value operational">${formatINR(netSavings)}</div>
            <div class="stat-card-footer">ROI: ${cost.roi.preventive_roi}x factor</div>
        </div>
        <div class="stat-card">
            <div class="stat-card-label">Plant Uptime</div>
            <div class="stat-card-value">${uptime}%</div>
            <div class="stat-card-footer">Target: 95.0%</div>
        </div>
        <div class="stat-card" onclick="document.getElementById('role-specific-section')?.scrollIntoView({ behavior: 'smooth' })" style="cursor: pointer;">
            <div class="stat-card-label">Pending Approvals</div>
            <div class="stat-card-value" style="color: ${pendingCount > 0 ? 'var(--status-warning)' : 'var(--text-primary)'}">${pendingCount}</div>
            <div class="stat-card-footer">ERP/SCADA actions queued (Click to view)</div>
        </div>
        <div class="stat-card">
            <div class="stat-card-label">Active Critical Alerts</div>
            <div class="stat-card-value critical">${stats.critical_alerts}</div>
            <div class="stat-card-footer">Immediate risk to production</div>
        </div>
        <div class="stat-card">
            <div class="stat-card-label">Preventive Ratio</div>
            <div class="stat-card-value">${cost.preventive_vs_reactive.preventive_ratio}%</div>
            <div class="stat-card-footer">Target: ${cost.preventive_vs_reactive.target_ratio}% (Tata Steel Std)</div>
        </div>
    `;
}

/**
 * Render role-specific container below fleet details.
 */
async function renderRoleSpecificSection() {
    const section = document.getElementById('role-specific-section');
    if (!section) return;

    const role = window.currentUserRole || 'engineer';

    if (role === 'engineer') {
        const problematicEq = dashboardData.equipment.filter(eq => eq.status !== 'operational');
        
        let checklistHTML = '';
        if (problematicEq.length === 0) {
            checklistHTML = `
                <div style="padding: 20px; text-align: center; color: var(--text-secondary);">
                    🟢 All equipment operational. No active checklists required.
                </div>
            `;
        } else {
            checklistHTML = problematicEq.map(eq => `
                <div class="engineer-checklist-card" style="margin-bottom: 12px; padding: 15px; background: rgba(255,255,255,0.02); border: 1px solid rgba(255,255,255,0.05); border-radius: var(--radius-md);">
                    <div style="display:flex; justify-content:space-between; margin-bottom: 8px;">
                        <h4 style="margin:0; font-size:13px; font-weight:600; color:var(--text-primary);">${eq.name} (${eq.id})</h4>
                        <span class="status-badge ${eq.status}">${eq.status}</span>
                    </div>
                    <ul style="list-style: none; padding-left: 0; margin: 0; font-size: 13px; color: var(--text-secondary);">
                        <li style="margin-bottom: 6px; display:flex; align-items:center; gap: 8px;">
                            <input type="checkbox" id="check-${eq.id}-1"> <label for="check-${eq.id}-1">Verify sensor wiring and connections</label>
                        </li>
                        <li style="margin-bottom: 6px; display:flex; align-items:center; gap: 8px;">
                            <input type="checkbox" id="check-${eq.id}-2"> <label for="check-${eq.id}-2">Check casing oil level & grease lubrication</label>
                        </li>
                        <li style="margin-bottom: 6px; display:flex; align-items:center; gap: 8px;">
                            <input type="checkbox" id="check-${eq.id}-3"> <label for="check-${eq.id}-3">Perform hand-held thermal probe measurement</label>
                        </li>
                    </ul>
                    <button class="quick-action" style="margin-top: 8px; font-size: 11px; padding: 4px 8px;" onclick="askAboutEquipment('${eq.id}', '${eq.name}')">
                        💬 Open AI Diagnostics Guide
                    </button>
                </div>
            `).join('');
        }

        section.innerHTML = `
            <div class="section-header" style="margin-top: 30px;">
                <h2 class="section-title">🛠— Field Maintenance Tasks & Checklists</h2>
            </div>
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
                <div class="stat-card" style="height: fit-content; text-align: left; padding: 20px;">
                    <h3 style="margin-top: 0; margin-bottom: 12px; font-size: 15px; color: var(--accent-primary);">Active Anomalies Tasks</h3>
                    ${checklistHTML}
                </div>
                <div class="stat-card" style="height: fit-content; text-align: left; padding: 20px;">
                    <h3 style="margin-top: 0; margin-bottom: 12px; font-size: 15px; color: var(--accent-primary);">Quick SOP Resources</h3>
                    <ul style="padding-left: 20px; font-size: 13px; line-height: 1.6; color: var(--text-secondary);">
                        <li><a href="#" onclick="switchView('knowledge'); return false;" style="color:var(--accent-primary); text-decoration:none;">SOP-BF-001: Blast Furnace Tuyere Thermal Inspection Manual</a></li>
                        <li><a href="#" onclick="switchView('knowledge'); return false;" style="color:var(--accent-primary); text-decoration:none;">SOP-CCM-001: Segment Roller Bearing Alignment and Torque Spec</a></li>
                        <li><a href="#" onclick="switchView('knowledge'); return false;" style="color:var(--accent-primary); text-decoration:none;">SOP-HRM-001: Hot Mill Work Roll Chock Lubrication SOP</a></li>
                    </ul>
                </div>
            </div>
        `;

    } else if (role === 'supervisor') {
        try {
            const result = await apiRequest('/api/alerts?acknowledged=0&limit=5');
            const alerts = result.data || [];
            
            let alertsHTML = '';
            if (alerts.length === 0) {
                alertsHTML = `
                    <tr>
                        <td colspan="5" style="text-align: center; padding: 20px; color: var(--text-secondary);">
                            🟢 No active alerts. All resolved!
                        </td>
                    </tr>
                `;
            } else {
                alertsHTML = alerts.map(a => `
                    <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
                        <td style="padding: 10px; font-weight:600; color:var(--text-primary);">${a.equipment_name}</td>
                        <td style="padding: 10px;"><span class="status-badge ${a.severity}">${a.severity}</span></td>
                        <td style="padding: 10px; max-width: 250px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">${a.title}</td>
                        <td style="padding: 10px; font-size: 11px; color: var(--text-secondary);">${new Date(a.timestamp).toLocaleTimeString()}</td>
                        <td style="padding: 10px; display:flex; gap: 8px;">
                            <button class="quick-action" style="font-size: 11px; padding: 4px 8px; margin:0;" onclick="ackAlertFromDashboard(${a.id})">Acknowledge</button>
                            <button class="quick-action" style="font-size: 11px; padding: 4px 8px; margin:0; background: rgba(16, 185, 129, 0.1); border-color: rgba(16,185,129,0.3); color:#10b981;" onclick="resolveAlertFromDashboard(${a.id})">Resolve</button>
                        </td>
                    </tr>
                `).join('');
            }

            section.innerHTML = `
                <div class="section-header" style="margin-top: 30px;">
                    <h2 class="section-title">🚨 Active Alerts Dispatch Queue</h2>
                </div>
                <div class="stat-card" style="padding: 20px; text-align: left; width: 100%; overflow-x: auto;">
                    <table style="width: 100%; border-collapse: collapse; text-align: left; font-size: 13px;">
                        <thead>
                            <tr style="border-bottom: 1px solid rgba(255,255,255,0.1); color: var(--text-secondary);">
                                <th style="padding: 10px 10px 5px 10px;">Equipment</th>
                                <th style="padding: 5px;">Severity</th>
                                <th style="padding: 5px;">Alert</th>
                                <th style="padding: 5px;">Time</th>
                                <th style="padding: 5px;">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${alertsHTML}
                        </tbody>
                    </table>
                </div>
            `;
        } catch (error) {
            console.error('Failed to load supervisor alerts:', error);
        }

    } else if (role === 'manager') {
        try {
            const result = await apiRequest('/api/dashboard/actions?limit=8');
            const actions = result.data || [];
            
            let actionsHTML = '';
            const pendingActions = actions.filter(a => a.status === 'pending');
            const otherActions = actions.filter(a => a.status !== 'pending');
            const sortedActions = [...pendingActions, ...otherActions];

            if (actions.length === 0) {
                actionsHTML = `
                    <tr>
                        <td colspan="6" style="text-align: center; padding: 20px; color: var(--text-secondary);">
                            ℹ️ No ERP/SCADA actions generated by AI agents yet.
                        </td>
                    </tr>
                `;
            } else {
                actionsHTML = sortedActions.map(a => {
                    let btnHTML = '';
                    if (a.status === 'pending') {
                        btnHTML = `
                            <button class="quick-action" style="font-size: 11px; padding: 4px 8px; margin: 0; background: rgba(16, 185, 129, 0.15); border-color: rgba(16, 185, 129, 0.4); color: #10b981;" onclick="handleActionApproval(${a.id}, 'approved')">Approve</button>
                            <button class="quick-action" style="font-size: 11px; padding: 4px 8px; margin: 0; background: rgba(239, 68, 68, 0.15); border-color: rgba(239, 68, 68, 0.4); color: #ef4444;" onclick="handleActionApproval(${a.id}, 'cancelled')">Reject</button>
                        `;
                    } else {
                        btnHTML = `<span style="font-size: 11px; font-weight:600; text-transform: uppercase; color: ${a.status === 'approved' ? '#10b981' : '#9ca3af'}">${a.status}</span>`;
                    }
                    
                    let actionTypeLabel = a.action_type.replace('_', ' ').toUpperCase();
                    let typeColor = 'var(--text-secondary)';
                    if (a.action_type === 'shutdown_equipment') typeColor = 'var(--status-critical)';
                    else if (a.action_type === 'order_part') typeColor = 'var(--accent-primary)';
                    
                    return `
                        <tr style="border-bottom: 1px solid rgba(255,255,255,0.05); opacity: ${a.status === 'pending' ? 1.0 : 0.6}">
                            <td style="padding: 10px; font-weight:600; color:var(--text-primary);">${a.equipment_name}</td>
                            <td style="padding: 10px; font-weight:600; font-size:11px; color: ${typeColor};">${actionTypeLabel}</td>
                            <td style="padding: 10px;">${a.details}</td>
                            <td style="padding: 10px;"><span class="dt-node-card-status ${a.status}">${a.status}</span></td>
                            <td style="padding: 10px; font-size: 11px; color: var(--text-secondary);">${new Date(a.timestamp).toLocaleTimeString()}</td>
                            <td style="padding: 10px; display:flex; gap: 8px;">
                                ${btnHTML}
                            </td>
                        </tr>
                    `;
                }).join('');
            }

            section.innerHTML = `
                <div class="section-header" style="margin-top: 30px;">
                    <h2 class="section-title">👔 ERP & SCADA Actions Pending Approval</h2>
                </div>
                <div class="stat-card" style="padding: 20px; text-align: left; width: 100%; overflow-x: auto;">
                    <table style="width: 100%; border-collapse: collapse; text-align: left; font-size: 13px;">
                        <thead>
                            <tr style="border-bottom: 1px solid rgba(255,255,255,0.1); color: var(--text-secondary);">
                                <th style="padding: 10px 10px 5px 10px;">Equipment</th>
                                <th style="padding: 5px;">Type</th>
                                <th style="padding: 5px;">Details</th>
                                <th style="padding: 5px;">Status</th>
                                <th style="padding: 5px;">Generated At</th>
                                <th style="padding: 5px;">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${actionsHTML}
                        </tbody>
                    </table>
                </div>
            `;
        } catch (error) {
            console.error('Failed to load manager actions:', error);
        }
    }
}

/**
 * Supervisor Dashboard Actions
 */
async function ackAlertFromDashboard(id) {
    try {
        await apiRequest(`/api/alerts/${id}`, {
            method: 'POST',
            body: JSON.stringify({ action: 'acknowledge' }),
        });
        showToast('Alert acknowledged', 'success');
        loadDashboardStats();
        loadEquipment();
    } catch (error) {
        console.error('Failed to acknowledge alert:', error);
    }
}

async function resolveAlertFromDashboard(id) {
    try {
        await apiRequest(`/api/alerts/${id}`, {
            method: 'POST',
            body: JSON.stringify({ action: 'resolve' }),
        });
        showToast('Alert resolved', 'success');
        loadDashboardStats();
        loadEquipment();
    } catch (error) {
        console.error('Failed to resolve alert:', error);
    }
}

/**
 * Manager Dashboard Actions
 */
async function handleActionApproval(id, status) {
    try {
        await apiRequest(`/api/dashboard/actions/${id}/status`, {
            method: 'POST',
            body: JSON.stringify({ status }),
        });
        showToast(`Action ${status === 'approved' ? 'approved' : 'rejected'}`, status === 'approved' ? 'success' : 'info');
        loadDashboardStats();
        loadEquipment();
    } catch (error) {
        console.error('Failed to update action status:', error);
    }
}


/* ═══════════════════════════════════════════════════════════════
   Demo Scenarios — Proactive Failure Detection
   ═══════════════════════════════════════════════════════════════ */

/**
 * Load the available demo scenarios and render the trigger cards.
 */
async function loadScenarios() {
    const grid = document.getElementById('scenario-grid');
    if (!grid) return;

    try {
        const result = await apiRequest('/api/scenarios/list');
        const scenarios = result.data || [];

        const sevEmoji = { critical: '🔴', high: '🟠', medium: '🟡', low: '🟢' };

        grid.innerHTML = scenarios.map(s => `
            <div class="scenario-card" id="scenario-${s.id}"
                 onclick="triggerScenario('${s.id}', this)">
                <div class="scenario-card-name">${sevEmoji[s.severity] || '⚪'} ${s.name}</div>
                <div class="scenario-card-desc">${s.description}</div>
                <div class="scenario-card-eq">${s.equipment_id} · ${s.severity.toUpperCase()}</div>
            </div>
        `).join('');
    } catch (error) {
        console.error('Failed to load scenarios:', error);
        grid.innerHTML = '<div style="color: var(--text-muted); font-size: 12px;">Scenarios unavailable.</div>';
    }
}

/**
 * Trigger a demo scenario. Injects degradation + alerts on the backend
 * and reflects the change live on the dashboard.
 */
async function triggerScenario(scenarioId, cardEl) {
    if (cardEl) {
        cardEl.classList.add('triggered');
        cardEl.style.pointerEvents = 'none';
    }

    try {
        const result = await apiRequest('/api/scenarios/trigger', {
            method: 'POST',
            body: JSON.stringify({ scenario_id: scenarioId }),
        });

        if (result.success) {
            showToast(result.data.message || 'Scenario triggered', 'warning');
            // Refresh dashboard state so status + health rings reflect the change.
            await Promise.all([loadDashboardStats(), loadEquipment()]);
        } else {
            showToast(result.error || 'Failed to trigger scenario', 'error');
            if (cardEl) {
                cardEl.classList.remove('triggered');
                cardEl.style.pointerEvents = '';
            }
        }
    } catch (error) {
        console.error('Failed to trigger scenario:', error);
        showToast('Failed to trigger scenario', 'error');
        if (cardEl) {
            cardEl.classList.remove('triggered');
            cardEl.style.pointerEvents = '';
        }
    }
}

/**
 * Reset all equipment back to operational and clear scenario state.
 */
async function resetScenarios() {
    try {
        const result = await apiRequest('/api/scenarios/reset', { method: 'POST' });
        if (result.success) {
            showToast('All equipment reset to operational', 'success');
            document.querySelectorAll('.scenario-card.triggered').forEach(card => {
                card.classList.remove('triggered');
                card.style.pointerEvents = '';
            });
            await Promise.all([loadDashboardStats(), loadEquipment()]);
        }
    } catch (error) {
        console.error('Failed to reset scenarios:', error);
        showToast('Failed to reset scenarios', 'error');
    }
}
